name: talepreview
description: Take home challenge - Mobile Developer

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3          # Flutter BLoC Library
  auto_route: ^7.2.0            # Auto_Route router
  easy_localization: ^3.0.2     # Translations
  flutter_lints: ^2.0.0         # Linting
  dotted_border: ^2.0.0+3
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.8.4
  dio: ^5.2.0       # Dotted Border
  auto_size_text: ^3.0.0
  mongo_dart: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1  # Auto_Route generator
  build_runner: ^2.4.4          # Build Runner
  json_serializable: ^6.7.0     # Json serializable

flutter:
  uses-material-design: true

  assets:
    - assets/books.png
    - assets/translations/
    - assets/lorem-ipsum.txt
